name: Test Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: project

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Verify Android Folder
        run: |
          pwd
          ls -la
          ls -la android
          ls -la android/gradle/wrapper

      - name: Test Gradle Wrapper
        run: |
          cd android
          chmod +x gradlew
          ./gradlew --version
