name: Build Android AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: project

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Dependencies
        run: npm install

      - name: Create Capacitor Assets Directory
        run: |
          mkdir -p android/app/src/main/assets
          mkdir -p android/app/src/main/res

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build Android AAB
        run: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease --stacktrace --no-daemon

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: servyfast-aab
          path: project/android/app/build/outputs/bundle/release/*.aab
