name: Build Android AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: project

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Dependencies
        run: npm install

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build Android AAB
  run: |
    pwd
    ls -la
    ls -la android
    cd android
    chmod +x gradlew
    ls -la
    cat gradle/wrapper/gradle-wrapper.properties
    ./gradlew --version --no-daemon

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: servyfast-aab
          path: project/android/app/build/outputs/bundle/release/*.aab
